# Generated by Django 5.2 on 2025-07-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_alter_usuario_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
