# Generated by Django 5.2 on 2025-07-20 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0002_crear_admin'),
        ('HistorialA', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistorialUsuario',
            new_name='HistorialAdmin',
        ),
    ]
