# Generated by Django 5.2 on 2025-07-21 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0002_crear_admin'),
        ('HistorialA', '0002_rename_historialusuario_historialadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialadmin',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historialA', to='Administrador.administrador'),
        ),
    ]
