# Generated by Django 5.2 on 2025-07-12 20:33

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
       
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('passwo', models.CharField(max_length=100)),
            ],
        ),
    ]
