# Generated by Django 5.2 on 2025-07-12 20:33

from django.db import migrations, models
from django.contrib.auth.hashers import make_password

def crear_admin(apps, schema_editor):
    Administrador = apps.get_model('Administrador', 'Administrador')
    if not Administrador.objects.filter(user='adminmo').exists():
        Administrador.objects.create(
            user='adminmo',
            passwo=make_password('inmo0708')
        )
class Migration(migrations.Migration):

    initial = True

    dependencies = [
       
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('passwo', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(crear_admin),
    ]
