# Generated by Django 5.2 on 2025-07-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicaciones', '0002_propiedad_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.FileField(upload_to='propiedades/'),
        ),
    ]
