# Generated by Django 5.2 on 2025-07-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicaciones', '0003_alter_propiedad_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
